---
- hosts: web
  remote_user: ec2-user
  become: yes
  become_method: sudo 
  
  tasks:
    - name:  Docker pull
      shell: docker pull 984994506673.dkr.ecr.us-east-2.amazonaws.com/hello-world

    - name:  Docker run
      shell: docker run --name nginx -d -p 80:80 nginx
